# Preload wallpapers into memory
#preload = ~/.config/wallpapers/minimal-1.jpg
#preload = ~/.config/wallpapers/minimal-2.jpg
#preload = ~/.config/wallpapers/minimal-3.jpg
preload = /home/sayan/.config/wallpapers/minimal-4.jpg

# Assign wallpaper to your laptop screen
wallpaper = eDP-1,/home/sayan/.config/wallpapers/minimal-4.jpg

# Optional: turn off splash screen
splash = false
